name: Docs

on:
  push:
    branches:
      - master
    paths:
      - docs/**
      - bqplot/**
      - mkdocs.yml
  pull_request:
    branches:
      - '*'
    paths:
      - docs/**
      - bqplot/**
      - mkdocs.yml

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@main
        with:
          environment-file: 'docs/mkdocs-environment.yml'
          channels: conda-forge

      - name: Discover typos with codespell
        run: codespell --ignore-words-list="afterall,curvelinear,hist" --skip="share,.git/*,js/*,*.csv,*.json,*.lock,*.map"

      - name: Build the docs site
        run: mkdocs build --site-dir dist

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    if: github.ref == 'refs/heads/master'
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
