name: Deploy docs

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          micromamba-version: '0.22.0'
          environment-file: 'docs/mkdocs-environment.yml'

      - name: Build the JupyterLite site
        shell: bash -l {0}
        run: mkdocs gh-deploy --force
